version: '3.3'
services:
 docker_term_app:
  env_file: 
    - var.env
  build: 
   context: .
   dockerfile: Dockerfile
   target: dev
  container_name: term_app
  volumes:
    - ./:/usr/src/app
  command: 'npm run start:dev'
