version: '3.3'
services:
 docker_term_app:
  env_file: 
    - .env
  build: 
   context: .
   dockerfile: Dockerfile
   target: "${TARGET_BUILD}"
  ports:
    - "${HOST_PORT}:${SERVER_PORT}" 
  container_name: term_app
  volumes:
    - ./:/usr/src/app
  command: 'npm run start:dev'
